from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from sekaisync.config import SiteSettings, load_site_profile


GITHUB_MASTER_BASE = "https://github.com/Sekai-World"
GITHUB_PAGES_MASTER_BASE = "https://sekai-world.github.io"
ASSET_CDN_BASE = "https://storage.sekai.best"
MASTER_API_BASE = "https://api.sekai.best"
ALTSOURCE_NEWS_BASE = "https://baijing.exmeaning.com"


SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "master_db",
        "label": "Structured master metadata",
        "status": "available",
        "fetcher": "fetch_region",
        "source_urls": [
            f"{GITHUB_MASTER_BASE}/sekai-master-db-diff",
            f"{GITHUB_MASTER_BASE}/sekai-master-db-en-diff",
            f"{GITHUB_MASTER_BASE}/sekai-master-db-tc-diff",
            f"{GITHUB_MASTER_BASE}/sekai-master-db-kr-diff",
            f"{GITHUB_MASTER_BASE}/sekai-master-db-cn-diff",
            f"{GITHUB_PAGES_MASTER_BASE}",
        ],
        "note": "JSON metadata only: characters, units, cards, songs, events, gachas, areas, stamps, missions, items.",
    },
    {
        "key": "official_localized_names",
        "label": "Official localized names in region master JSON",
        "status": "available",
        "fetcher": "merge_glossary",
        "source_urls": [],
        "note": "Derived from the region master DB; JP is the source-language set.",
    },
    {
        "key": "story_metadata",
        "label": "Story episode titles, outlines and scenario IDs",
        "status": "partial",
        "fetcher": "fetch_region",
        "source_urls": [
            f"{GITHUB_PAGES_MASTER_BASE}/sekai-master-db-diff/eventStories.json",
            f"{GITHUB_PAGES_MASTER_BASE}/sekai-master-db-diff/unitStories.json",
            f"{GITHUB_PAGES_MASTER_BASE}/sekai-master-db-diff/cardEpisodes.json",
            f"{GITHUB_PAGES_MASTER_BASE}/sekai-master-db-diff/specialStories.json",
        ],
        "note": "Contains titles/outlines and scenario IDs, not the complete scenario text.",
    },
    {
        "key": "story_full_text",
        "label": "Complete scenario dialogue",
        "status": "partial",
        "fetcher": "crawl_altsource_sv / crawl_altsource_ms",
        "source_urls": [
            f"{ASSET_CDN_BASE}",
            "https://storage.exmeaning.com",
        ],
        "note": "Localized scenario JSON/text is served by community CDNs; full text requires an opt-in TOS-consented crawl.",
    },
    {
        "key": "binary_assets",
        "label": "Images, audio, Live2D and video bytes",
        "status": "missing",
        "fetcher": "none",
        "source_urls": [f"{ASSET_CDN_BASE}"],
        "note": "Kept outside GitHub by asset updaters; do not bundle into the knowledge store.",
    },
    {
        "key": "music_charts",
        "label": "Rendered music charts",
        "status": "missing",
        "fetcher": "none",
        "source_urls": [f"{GITHUB_MASTER_BASE}/sekai-charts-updater"],
        "note": "Generated by a separate updater and served remotely.",
    },
    {
        "key": "official_news",
        "label": "Official news and announcements",
        "status": "missing",
        "fetcher": "sync_news",
        "source_urls": [
            f"{GITHUB_PAGES_MASTER_BASE}",
            f"{ALTSOURCE_NEWS_BASE}",
        ],
        "note": "Official in-game news comes from region userInformations.json plus the auxiliary news mirror; "
        "Sekai Viewer site announcements are excluded.",
    },
    {
        "key": "player_dynamic_data",
        "label": "Player ranking and profile data",
        "status": "missing",
        "fetcher": "none",
        "source_urls": [],
        "note": "Dynamic player data is not part of master DB; has privacy and terms-of-service risk.",
    },
    {
        "key": "web_text",
        "label": "Crawled text index from altsource_sv / altsource_ms",
        "status": "missing",
        "fetcher": "crawl_altsource_ms / crawl_altsource_sv",
        "source_urls": [
            "https://pjsk.moe/sitemap.xml",
            "https://metadata.exmeaning.com",
            "https://storage.exmeaning.com",
            "https://sekai-world.github.io",
        ],
        "note": "Text-only web import. Requires explicit TOS consent before crawling. "
        "Translation reference pages are fetched together with the story crawl and trust-graded.",
    },
]


def _site_source_urls(sites: Optional[Iterable[SiteSettings]]) -> dict[str, list[str]]:
    """Per-key dynamic URLs derived from the enabled site profile.

    Only the site-driven layers follow the profile:

    - ``story_full_text`` / ``web_text``: crawled community-site content;
    - ``official_news``: the news mirror part (``news_base``).

    The GitHub master fact layer stays fixed regardless of site config:
    ``master_db``, ``story_metadata``, ``official_localized_names``,
    ``binary_assets`` and the region ``userInformations.json`` news source
    are clone/tarball-derived master data and never follow the sites list.
    """
    if sites is None:
        sites = load_site_profile(Path(__file__).resolve().parent.parent)
    enabled = [site for site in sites if site.enabled]
    ms_instances = [site.moesekai for site in enabled if site.moesekai is not None]
    sv_instances = [site.viewer for site in enabled if site.viewer is not None]

    def unique(values: Iterable[str]) -> list[str]:
        seen: set[str] = set()
        result: list[str] = []
        for value in values:
            if value not in seen:
                seen.add(value)
                result.append(value)
        return result

    story_asset_urls: list[str] = []
    for sv in sv_instances:
        story_asset_urls.append(sv.asset_base)
    for ms in ms_instances:
        story_asset_urls.extend(ms.asset_bases)

    web_text_urls: list[str] = []
    for ms in ms_instances:
        web_text_urls.append(ms.sitemap_url)
        web_text_urls.extend(ms.metadata_bases)
    for sv in sv_instances:
        web_text_urls.append(sv.master_base)

    # Region userInformations.json is master data served from GitHub Pages;
    # only the news mirror endpoint follows the configured instances.
    news_urls: list[str] = [GITHUB_PAGES_MASTER_BASE]
    for ms in ms_instances:
        news_urls.append(ms.news_base)

    return {
        "story_full_text": unique(story_asset_urls),
        "web_text": unique(web_text_urls),
        "official_news": unique(news_urls),
    }


def build_source_manifest(sites: Optional[Iterable[SiteSettings]] = None) -> list[dict[str, Any]]:
    dynamic = _site_source_urls(sites)
    return [
        {
            "key": item["key"],
            "label": item["label"],
            "status": item["status"],
            "fetcher": item["fetcher"],
            "source_urls": dynamic.get(item["key"], list(item["source_urls"])),
            "note": item["note"],
        }
        for item in SOURCE_CATALOG
    ]


def build_coverage(
    region: str,
    demo: bool = False,
    web_status: dict[str, Any] | None = None,
    news_available: bool | None = False,
    master_available: bool | None = True,
) -> dict[str, dict[str, str]]:
    coverage: dict[str, dict[str, str]] = {}
    for item in SOURCE_CATALOG:
        if demo:
            coverage[item["key"]] = {
                "status": "demo",
                "note": "Synthetic fixtures only; not production ground truth.",
            }
            continue
        coverage[item["key"]] = {
            "status": str(item["status"]),
            "note": str(item["note"]),
        }
    if not demo:
        coverage["official_localized_names"]["note"] = (
            "Source-language names for jp; official localized names for en/tc/kr/cn."
        )
        if master_available is None:
            for key in ("master_db", "official_localized_names", "story_metadata"):
                coverage[key] = {"status": "unknown", "note": "No region master measurement was supplied."}
        elif not master_available:
            missing_note = (
                "No local master source directory; run sekaisync sync --regions "
                + region
                + " before measuring this region."
            )
            for key in ("master_db", "official_localized_names", "story_metadata"):
                coverage[key] = {"status": "missing", "note": missing_note}
            coverage["story_full_text"] = {
                "status": "partial",
                "note": "Web text may exist, but the region master is missing so completeness cannot be measured.",
            }
        # `None` means "no region-scoped measurement exists yet": a global or
        # another region's positive signal must not be presented as this
        # region's state (Astra P18), so the row degrades to ``unknown``
        # instead of available/missing.
        if web_status is None:
            web_state = "unknown"
            web_note = "No region-scoped web status was supplied for this region."
        elif bool(web_status.get("enabled")):
            web_state = "available"
            web_note = "Crawled pages exist locally."
        else:
            web_state = "missing"
            web_note = "Run sekaisync crawl and accept the TOS first."
        coverage["web_text"] = {"status": web_state, "note": web_note}
        category_counts = (web_status or {}).get("category_counts") or {}
        text_categories = {
            "mainline",
            "event_story",
            "card_story",
            "special_story",
            "virtual_live",
            "area_dialogue",
            "character_voice",
            "mysekai",
        }
        if any(
            count > 0
            for source_counts in category_counts.values()
            if isinstance(source_counts, dict)
            for category, count in source_counts.items()
            if category in text_categories
        ) and master_available is True:
            coverage["story_full_text"]["status"] = "available"
            coverage["story_full_text"]["note"] = (
                "Localized story text is present in the crawled web store."
            )
    if not demo:
        if news_available is None:
            coverage["official_news"] = {
                "status": "unknown",
                "note": "No region-scoped news availability was supplied for this region.",
            }
        elif news_available:
            coverage["official_news"] = {
                "status": "available",
                "note": "Official news/announcements are stored in the news layer (store/news/news.json in v1, store/kb/news/*.json in v2).",
            }
    return coverage


def build_region_coverage(
    regions: Iterable[str],
    web_status: Any = None,
    news_available: Any = False,
    master_available: dict[str, bool] | None = None,
) -> dict[str, dict[str, dict[str, str]]]:
    """Accept region-keyed measurements; never infer region from global totals.

    Even a single selected region does not establish provenance for a global
    positive signal. Callers without regional measurements receive unknown.
    """
    master_available = master_available or {}
    global_web = isinstance(web_status, dict) and any(
        key in web_status for key in ("enabled", "category_counts", "sources")
    )
    regions = tuple(regions)
    result: dict[str, dict[str, dict[str, str]]] = {}
    for region in regions:
        if region == "demo":
            result[region] = build_coverage(region, demo=True)
            continue
        if isinstance(web_status, dict):
            # Only region-keyed mappings carry provenance; a global status
            # dict stays unknown for every region (P18).
            region_web = web_status.get(region) if not global_web else None
        else:
            region_web = None
        region_news: Optional[bool]
        if isinstance(news_available, dict):
            region_news = news_available.get(region)
        else:
            region_news = None
        result[region] = build_coverage(
            region,
            demo=False,
            web_status=region_web,
            news_available=region_news,
            master_available=master_available.get(region, None),
        )
    return result
