from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from sekaisync.config import REGIONS, SiteSettings, load_site_profile


#: Layers whose rows describe *where data comes from*.  The layer set, labels,
#: statuses and notes are product knowledge and stay here; every concrete URL is
#: resolved from configuration at call time (see :func:`_resolve_source_urls`), so
#: this module never hardcodes a particular instance's address.
#:
#: Background (2026-09-20): the catalog used to embed one specific deployment's
#: addresses (a GitHub org, two asset CDNs, a news mirror). That contradicted the
#: project's stated position — SekaiSync is compatible with the two public WebDB
#: *systems*, and naming one instance both leaks a local test configuration and
#: reads as an endorsement of that instance. URLs now come from the same config
#: the fetchers use, so the manifest can only report what this install is
#: actually configured to read.
SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "master_db",
        "label": "Structured master metadata",
        "status": "available",
        "fetcher": "fetch_region",
        "url_source": "master_repos",
        "note": "JSON metadata only: characters, units, cards, songs, events, gachas, areas, stamps, missions, items.",
    },
    {
        "key": "official_localized_names",
        "label": "Official localized names in region master JSON",
        "status": "available",
        "fetcher": "merge_glossary",
        "url_source": "none",
        "note": "Derived from the region master DB; JP is the source-language set.",
    },
    {
        "key": "story_metadata",
        "label": "Story episode titles, outlines and scenario IDs",
        "status": "partial",
        "fetcher": "fetch_region",
        "url_source": "master_story_tables",
        "note": "Contains titles/outlines and scenario IDs, not the complete scenario text.",
    },
    {
        "key": "story_full_text",
        "label": "Complete scenario dialogue",
        "status": "partial",
        "fetcher": "crawl_altsource_sv / crawl_altsource_ms",
        "url_source": "crawl_asset_bases",
        "note": "Localized scenario JSON/text is served by community CDNs; full text requires an opt-in TOS-consented crawl.",
    },
    {
        "key": "binary_assets",
        "label": "Images, audio, Live2D and video bytes",
        "status": "missing",
        "fetcher": "none",
        "url_source": "crawl_asset_bases",
        "note": "Kept outside GitHub by asset updaters; do not bundle into the knowledge store.",
    },
    {
        "key": "music_charts",
        "label": "Rendered music charts",
        "status": "missing",
        "fetcher": "none",
        "url_source": "none",
        "note": "Generated by a separate updater and served remotely; not part of this store.",
    },
    {
        "key": "official_news",
        "label": "Official news and announcements",
        "status": "missing",
        "fetcher": "sync_news",
        "url_source": "news_bases",
        "note": "Official in-game news comes from region userInformations.json plus the auxiliary news mirror; "
        "Sekai Viewer site announcements are excluded.",
    },
    {
        "key": "player_dynamic_data",
        "label": "Player ranking and profile data",
        "status": "missing",
        "fetcher": "none",
        "url_source": "none",
        "note": "Dynamic player data is not part of master DB; has privacy and terms-of-service risk.",
    },
    {
        "key": "web_text",
        "label": "Crawled text index from altsource_sv / altsource_ms",
        "status": "missing",
        "fetcher": "crawl_altsource_ms / crawl_altsource_sv",
        "url_source": "crawl_site_bases",
        "note": "Text-only web import. Requires explicit TOS consent before crawling. "
        "Translation reference pages are fetched together with the story crawl and trust-graded.",
    },
]


def _unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        text = str(value or "").strip()
        if text and text not in seen:
            seen.add(text)
            result.append(text)
    return result


def _master_repo_urls(config: Optional[Any]) -> list[str]:
    """Clone/tarball URLs for the region master repositories.

    Built from ``github_tarball_base`` + each region's ``repo_slug`` — the same
    two inputs ``fetcher`` downloads from, so the manifest cannot drift from
    what a sync actually fetches.
    """
    base = str(getattr(config, "github_tarball_base", "") or "").strip().rstrip("/")
    if not base:
        return []
    return _unique(f"{base}/{info.repo_slug}" for info in REGIONS.values() if info.repo_slug)


def _resolve_source_urls(url_source: str, config: Optional[Any]) -> list[str]:
    """Concrete URLs for one catalog row, resolved from configuration.

    An unconfigured install yields an empty list: the row still reports its
    label, status and note, but claims no address it was not given.
    """
    sites = _sites_for(config)
    enabled = [site for site in sites if site.enabled]
    ms_instances = [site.moesekai for site in enabled if site.moesekai is not None]
    sv_instances = [site.viewer for site in enabled if site.viewer is not None]

    if url_source == "master_repos":
        return _master_repo_urls(config)
    if url_source == "master_story_tables":
        return _unique(
            f"{url}/eventStories.json" for url in _master_repo_urls(config)
        )
    if url_source == "crawl_asset_bases":
        urls: list[str] = []
        for sv in sv_instances:
            urls.append(sv.asset_base)
        for ms in ms_instances:
            urls.extend(ms.asset_bases)
        return _unique(urls)
    if url_source == "crawl_site_bases":
        urls = []
        for ms in ms_instances:
            urls.append(ms.sitemap_url)
            urls.extend(ms.metadata_bases)
        for sv in sv_instances:
            urls.append(sv.master_base)
        return _unique(urls)
    if url_source == "news_bases":
        urls = []
        for ms in ms_instances:
            urls.append(ms.news_base)
        for sv in sv_instances:
            urls.append(sv.master_base)
        return _unique(urls)
    return []


def _sites_for(config: Optional[Any]) -> tuple[SiteSettings, ...]:
    """The site profile to report on: the caller's config, else the local one."""
    sites = getattr(config, "sites", None)
    if sites is not None:
        return tuple(sites)
    return load_site_profile(Path(__file__).resolve().parent.parent)


def build_source_manifest(
    sites: Optional[Iterable[SiteSettings]] = None,
    config: Optional[Any] = None,
) -> list[dict[str, Any]]:
    """Describe each data layer and the URLs this install is configured to read.

    ``sites`` overrides the site profile directly (tests, callers holding a
    profile); ``config`` supplies both the profile and the master-repository
    base. Without either, the local ``settings.json`` profile is used.
    """
    holder = config
    if holder is None and sites is not None:
        holder = _ConfigWithSites(tuple(sites))
    return [
        {
            "key": item["key"],
            "label": item["label"],
            "status": item["status"],
            "fetcher": item["fetcher"],
            "source_urls": _resolve_source_urls(item.get("url_source", "none"), holder),
            "note": item["note"],
        }
        for item in SOURCE_CATALOG
    ]


class _ConfigWithSites:
    """Minimal config stand-in for callers that only have a site profile."""

    def __init__(self, sites: tuple[SiteSettings, ...]) -> None:
        self.sites = sites
        self.github_tarball_base = ""


def build_coverage(
    region: str,
    demo: bool = False,
    web_status: dict[str, Any] | None = None,
    news_available: bool | None = False,
    master_available: bool | None = True,
) -> dict[str, dict[str, str]]:
    coverage: dict[str, dict[str, str]] = {}
    for item in SOURCE_CATALOG:
        if demo:
            coverage[item["key"]] = {
                "status": "demo",
                "note": "Synthetic fixtures only; not production ground truth.",
            }
            continue
        coverage[item["key"]] = {
            "status": str(item["status"]),
            "note": str(item["note"]),
        }
    if not demo:
        coverage["official_localized_names"]["note"] = (
            "Source-language names for jp; official localized names for en/tc/kr/cn."
        )
        if master_available is None:
            for key in ("master_db", "official_localized_names", "story_metadata"):
                coverage[key] = {"status": "unknown", "note": "No region master measurement was supplied."}
        elif not master_available:
            missing_note = (
                "No local master source directory; run sekaisync sync --regions "
                + region
                + " before measuring this region."
            )
            for key in ("master_db", "official_localized_names", "story_metadata"):
                coverage[key] = {"status": "missing", "note": missing_note}
            coverage["story_full_text"] = {
                "status": "partial",
                "note": "Web text may exist, but the region master is missing so completeness cannot be measured.",
            }
        # `None` means "no region-scoped measurement exists yet": a global or
        # another region's positive signal must not be presented as this
        # region's state (Astra P18), so the row degrades to ``unknown``
        # instead of available/missing.
        if web_status is None:
            web_state = "unknown"
            web_note = "No region-scoped web status was supplied for this region."
        elif bool(web_status.get("enabled")):
            web_state = "available"
            web_note = "Crawled pages exist locally."
        else:
            web_state = "missing"
            web_note = "Run sekaisync crawl and accept the TOS first."
        coverage["web_text"] = {"status": web_state, "note": web_note}
        category_counts = (web_status or {}).get("category_counts") or {}
        text_categories = {
            "mainline",
            "event_story",
            "card_story",
            "special_story",
            "virtual_live",
            "area_dialogue",
            "character_voice",
            "mysekai",
        }
        if any(
            count > 0
            for source_counts in category_counts.values()
            if isinstance(source_counts, dict)
            for category, count in source_counts.items()
            if category in text_categories
        ) and master_available is True:
            coverage["story_full_text"]["status"] = "available"
            coverage["story_full_text"]["note"] = (
                "Localized story text is present in the crawled web store."
            )
    if not demo:
        if news_available is None:
            coverage["official_news"] = {
                "status": "unknown",
                "note": "No region-scoped news availability was supplied for this region.",
            }
        elif news_available:
            coverage["official_news"] = {
                "status": "available",
                "note": "Official news/announcements are stored in the news layer (store/news/news.json in v1, store/kb/news/*.json in v2).",
            }
    return coverage


def build_region_coverage(
    regions: Iterable[str],
    web_status: Any = None,
    news_available: Any = False,
    master_available: dict[str, bool] | None = None,
) -> dict[str, dict[str, dict[str, str]]]:
    """Accept region-keyed measurements; never infer region from global totals.

    Even a single selected region does not establish provenance for a global
    positive signal. Callers without regional measurements receive unknown.
    """
    master_available = master_available or {}
    global_web = isinstance(web_status, dict) and any(
        key in web_status for key in ("enabled", "category_counts", "sources")
    )
    regions = tuple(regions)
    result: dict[str, dict[str, dict[str, str]]] = {}
    for region in regions:
        if region == "demo":
            result[region] = build_coverage(region, demo=True)
            continue
        if isinstance(web_status, dict):
            # Only region-keyed mappings carry provenance; a global status
            # dict stays unknown for every region (P18).
            region_web = web_status.get(region) if not global_web else None
        else:
            region_web = None
        region_news: Optional[bool]
        if isinstance(news_available, dict):
            region_news = news_available.get(region)
        else:
            region_news = None
        result[region] = build_coverage(
            region,
            demo=False,
            web_status=region_web,
            news_available=region_news,
            master_available=master_available.get(region, None),
        )
    return result
